project:
  type: book

book:
  title: "Contributor's Guide"
  author: "Norah Jones"
  date: "6/16/2025"
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - project-overview.qmd
        - communication-and-governance.qmd
    - part: "Contributing"
      chapters:
        - contributing.qmd
        - coding-standards.qmd
        - development-environment.qmd
    - part: "Development"
      chapters:
        - architecture.qmd
        - testing.qmd
        - documentation.qmd
    - part: "Deployment"
      chapters:
        - deployment.qmd
    - part: "Resources"
      chapters:
        - faq.qmd
        - resources.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



